title: Jacob Sussman
logo: /assets/headshot_img.png
description: Hi, my name is Jacob!
show_downloads: false
google_analytics:
remote_theme: pages-themes/minimal@v0.2.0
plugins:
- jekyll-remote-theme 
